version: "3.8"

services:
  postgres:
    image: postgres:18.1-alpine3.23
    container_name: audisoft-postgres
    environment:
      POSTGRES_USER: audisoft
      POSTGRES_PASSWORD: audisoft
      POSTGRES_DB: audisoft
    ports:
      - "20000:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U audisoft"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
