spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/audisoft
    username: audisoft
    password: audisoft-password
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    com.audisoft: DEBUG
    org.springframework.web: DEBUG
